"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Provider } from "react-redux";
import store from "@/store/store";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-screen min-h-screen relative overflow-x-hidden ${poppins.className}`}
      >
        <Provider store={store}>
          {" "}
          <GoogleOAuthProvider clientId="286890073941-1pu4m1gvl3cle29jnpv6qvkf04mu97m7.apps.googleusercontent.com">
            {" "}
            <Toaster position="top-center" />
            {children}
          </GoogleOAuthProvider>
        </Provider>
      </body>
    </html>
  );
}
