import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { NextAuthProvider } from "./providers";
import { Toaster } from 'react-hot-toast'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-screen min-h-screen relative overflow-x-hidden ${poppins.className}`}
      >
        {" "}
        <NextAuthProvider>
        <Toaster position="top-center" />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
